(function(root){'use strict';
const PUA=/[\uE000-\uF8FF]/u;
const MAP={
 Symbol:{0xF062:'β'},
 Wingdings:{0xF062:'♌'},
 'Wingdings 2':{},'Wingdings 3':{},Webdings:{}
};
const fontKey=n=>String(n||'').trim().replace(/^['"]|['"]$/g,'');
const cpLabel=cp=>`U+${cp.toString(16).toUpperCase().padStart(4,'0')}`;
function xmlDecode(s){return String(s||'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(+n)).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16)));}
function attrs(s){const o={};String(s||'').replace(/([\w:.-]+)\s*=\s*("([^"]*)"|'([^']*)')/g,(_,k,_q,a,b)=>(o[k]=xmlDecode(a===undefined?b:a),''));return o;}
function blocks(xml,tag){const re=new RegExp(`<${tag}\\b([^>]*?)(?:\\/\\s*>|>([\\s\\S]*?)<\\/${tag}>)`,'gi'),a=[];let m;while((m=re.exec(xml||'')))a.push({a:attrs(m[1]),b:m[2]||''});return a;}
function body(xml,tag){const m=new RegExp(`<${tag}\\b[^>]*>([\\s\\S]*?)<\\/${tag}>`,'i').exec(xml||'');return m?m[1]:'';}
function tagAttrs(xml,tag){const m=new RegExp(`<${tag}\\b([^>]*)\\/?(?:>|$)`,'i').exec(xml||'');return m?attrs(m[1]):{};}
function runFont(xml,fallback){const p=body(xml,'rPr'),rf=tagAttrs(p,'rFont');return fontKey(rf.val||fallback||'');}
function enrichCell(cell,font,richRuns){cell.sourceFontName=font.name||'';cell.sourceFontFamily=font.family||'';cell.sourceFontCharset=font.charset||'';cell.sourceFontScheme=font.scheme||'';if(richRuns?.length)cell.textRuns=richRuns;else cell.textRuns=[{text:String(cell.value??''),sourceFontName:font.name||'',sourceFontFamily:font.family||'',sourceFontCharset:font.charset||'',sourceFontScheme:font.scheme||''}];}
async function enrichWorkbook(arrayBuffer,wb){
 const zip=new JournalArchive.ZipReader(arrayBuffer,{maxEntries:2500,maxTotalUncompressed:120*1024*1024,maxEntryUncompressed:80*1024*1024,maxCompressionRatio:300,maxArchiveBytes:55*1024*1024});
 const text=async(name,opt=false)=>{const e=zip.entries.find(x=>x.name===name);if(!e){if(opt)return'';throw new Error(`XLSX пошкоджений: відсутній ${name}`);}return new TextDecoder().decode(await zip.readEntry(e));};
 const styles=await text('xl/styles.xml',true), shared=await text('xl/sharedStrings.xml',true), workbook=await text('xl/workbook.xml'), rels=await text('xl/_rels/workbook.xml.rels');
 const fonts=blocks(body(styles,'fonts'),'font').map(f=>{const n=tagAttrs(f.b,'name'),fam=tagAttrs(f.b,'family'),cs=tagAttrs(f.b,'charset'),sch=tagAttrs(f.b,'scheme');return{name:fontKey(n.val),family:fam.val||'',charset:cs.val||'',scheme:sch.val||''};});
 const xfs=blocks(body(styles,'cellXfs'),'xf').map(x=>+x.a.fontId||0);
 const sharedRuns=blocks(shared,'si').map(si=>{const rs=blocks(si.b,'r');if(!rs.length)return null;return rs.map(r=>({text:blocks(r.b,'t').map(t=>xmlDecode(t.b)).join(''),sourceFontName:runFont(r.b,''),sourceFontFamily:'',sourceFontCharset:'',sourceFontScheme:''}));});
 const rel={};for(const r of blocks(rels,'Relationship'))if(r.a.Id)rel[r.a.Id]=r.a.Target;
 const sheetPaths=[];for(const s of blocks(body(workbook,'sheets'),'sheet')){let t=rel[s.a['r:id']]||'';t=t.replace(/^\//,'');if(!t.startsWith('xl/'))t='xl/'+t.replace(/^\.\//,'');sheetPaths.push(t.replace(/xl\/worksheets\/\.\.\//,'xl/'));}
 for(let i=0;i<wb.sheets.length;i++){const sh=wb.sheets[i],sx=await text(sheetPaths[i],true);for(const c of blocks(sx,'c')){const ref=c.a.r,cell=sh.cells.get(ref);if(!cell)continue;const fi=xfs[+c.a.s||0]||0,font=fonts[fi]||{};let rr=null;if(c.a.t==='s'){const v=body(c.b,'v');rr=sharedRuns[+v]||null;}else if(c.a.t==='inlineStr'){const rs=blocks(body(c.b,'is'),'r');if(rs.length)rr=rs.map(r=>({text:blocks(r.b,'t').map(t=>xmlDecode(t.b)).join(''),sourceFontName:runFont(r.b,font.name),sourceFontFamily:font.family||'',sourceFontCharset:font.charset||'',sourceFontScheme:font.scheme||''}));}enrichCell(cell,font,rr);}}
 return wb;
}
const origParse=JournalWorkbook.parseWorkbook.bind(JournalWorkbook);JournalWorkbook.parseWorkbook=async function(buf,file){const wb=await origParse(buf,file);return enrichWorkbook(buf,wb);};
function mapText(text,font){let out='',audit=[],unknown=[];for(const ch of String(text??'')){const cp=ch.codePointAt(0);if(cp>=0xE000&&cp<=0xF8FF){const f=fontKey(font),mapped=MAP[f]?.[cp];if(mapped){out+=mapped;audit.push({originalCodePoint:cpLabel(cp),sourceFont:f,resultingUnicode:mapped,resultingCodePoint:cpLabel(mapped.codePointAt(0))});}else{out+=ch;unknown.push({codePoint:cpLabel(cp),sourceFont:f||'невідомий'});}}else out+=ch;}return{out,audit,unknown};}
function provenance(wb,file,sheet,ref){const c=wb.sheets.find(s=>s.name===sheet)?.cells.get(ref);return c?{sourceFontName:c.sourceFontName||'',sourceFontFamily:c.sourceFontFamily||'',textRuns:c.textRuns||[]}:{};}
function patchDiscipline(result,wb){const d=result.discipline;let found=0,mapped=0;const warns=[];const seen=new Set();const visit=obj=>{if(!obj||typeof obj!=='object'||seen.has(obj))return;seen.add(obj);if(Array.isArray(obj)){obj.forEach(visit);return;}if(Array.isArray(obj.sources)){for(const src of obj.sources){const p=provenance(wb,src.file,src.sheet,src.cell);Object.assign(src,p);const runs=p.textRuns?.length?p.textRuns:[{text:src.text,sourceFontName:p.sourceFontName||''}];let text='',aud=[];for(const r of runs){const m=mapText(r.text,r.sourceFontName||p.sourceFontName);text+=m.out;found+=(m.audit.length+m.unknown.length);mapped+=m.audit.length;aud.push(...m.audit);for(const u of m.unknown){const id=`font|${src.key}|${u.codePoint}`;warns.push({id,kind:'font_symbol',category:'font_symbol',groupKey:`${u.sourceFont}|${u.codePoint}`,file:src.file,subject:d.subject,sheet:src.sheet,cell:src.cell,original:src.text,columnContext:'font/symbol',sourceFontName:u.sourceFont,codePoint:u.codePoint,message:`Нестандартний символ шрифту ${u.codePoint}. Вихідний шрифт: ${u.sourceFont}. Автоматичне перетворення неоднозначне; «Залишити» можливе лише якщо фінальний PDF-шрифт підтримує символ.`,correctable:true,requiresDecision:true,allowReplace:true});}}if(aud.length){src.text=text;src.pdfText=text;src.fontNormalizationAudit=aud;if(obj.sources.length===1)obj.pdfText=text;}}}for(const v of Object.values(obj))visit(v);};visit(d);d.stats=d.stats||{};d.stats.puaSymbolsFound=found;d.stats.puaAutoMapped=mapped;return warns;}
const origAnalyze=JournalParser.analyzeWorkbook.bind(JournalParser);JournalParser.analyzeWorkbook=function(wb){const r=origAnalyze(wb);r.warnings.push(...patchDiscipline(r,wb));return r;};
function allSources(ds){const out=[],seen=new Set();const visit=o=>{if(!o||typeof o!=='object'||seen.has(o))return;seen.add(o);if(Array.isArray(o)){o.forEach(visit);return;}if(Array.isArray(o.sources))out.push(...o.sources);for(const v of Object.values(o))visit(v);};ds.forEach(visit);return out;}
function fontIssues(ds,overrides,font){const issues=[];for(const s of allSources(ds)){let t=s.pdfText??s.text??'';const o=overrides?.[s.key];if(o?.mode==='blank')t='';else if(o?.mode==='replace')t=o.value??'';for(const ch of String(t)){const cp=ch.codePointAt(0);if(!font.hasCodePoint(cp))issues.push({file:s.file,subject:ds.find(d=>d.file===s.file)?.subject||'',sheet:s.sheet,cell:s.cell,sourceFontName:s.sourceFontName||'',codePoint:cpLabel(cp),text:String(t)});}}return issues;}
JournalValidation.fontIssues=fontIssues;JournalValidation.PUA_MAP=MAP;JournalValidation.mapFontDependentText=mapText;
JournalValidation.buildTechnicalReport=function(r={}){const st=r.stats||r.stats===0?r.stats:{};return [`Journal PDF v${r.version||'1.2.2'}`,`Браузер: ${r.browser||(typeof navigator!=='undefined'?navigator.userAgent:'')}`,`Етап: ${r.stage||''}`,`Файл: ${r.file||''}`,`Дисципліна: ${r.subject||''}`,`Аркуш: ${r.sheet||''}`,`Клітинка: ${r.cell||''}`,`Вихідний шрифт: ${r.sourceFontName||''}`,`Код: ${r.codePoint||''}`,`Текст клітинки: ${r.cellText||''}`,`Тип: ${r.errorType||r.kind||''}`,`Знайдено предметів: ${st.subjectsFound??''}`,`Автонормалізацій: ${st.autoNormalizations??''}`,`Потребують рішення: ${st.decisionRequired??''}`,`Прийнято рішень: ${st.decisionsAccepted??''}`,`Пропущено порожніх grade-pages: ${st.emptyGradePagesSkipped??''}`,`PUA знайдено: ${st.puaSymbolsFound??''}`,`PUA auto-mapped: ${st.puaAutoMapped??''}`,`PUA потребують рішення: ${st.puaDecisionRequired??''}`,`Технічний текст: ${r.message||''}`].join('\n');};
root.JournalV122={enrichWorkbook,mapText,fontIssues,cpLabel};
})(typeof globalThis!=='undefined'?globalThis:self);