(function(root){'use strict';
const GREEK=[['α','альфа'],['β','бета'],['γ','гамма'],['δ','дельта'],['ε','епсилон'],['ζ','дзета'],['η','ета'],['θ','тета'],['ι','йота'],['κ','каппа'],['λ','лямбда'],['μ','мю'],['ν','ню'],['ξ','ксі'],['ο','омікрон'],['π','пі'],['ρ','ро'],['σ','сигма'],['τ','тау'],['υ','іпсилон'],['φ','фі'],['χ','хі'],['ψ','псі'],['ω','омега']];
const cp=s=>`U+${s.codePointAt(0).toString(16).toUpperCase().padStart(4,'0')}`;
function context(text,codePoint,radius=32){text=String(text||'');const target=String.fromCodePoint(parseInt(String(codePoint).replace(/^U\+/i,''),16));let i=text.indexOf(target);if(i<0)return{before:text.slice(0,64),symbol:'',after:text.length>64?'…':'',position:-1,full:text};const a=Math.max(0,i-radius),b=Math.min(text.length,i+target.length+radius);return{before:(a?'…':'')+text.slice(a,i),symbol:target,after:text.slice(i+target.length,b)+(b<text.length?'…':''),position:i+1,full:text};}
function groupKey(w){return`${w.category||w.kind||''}|${w.codePoint||w.original||''}|${String(w.sourceFontName||'').trim().toLowerCase()}|${w.columnContext||''}`;}
function isFont(w){return w&&(w.category==='font_symbol'||w.kind==='font_symbol'||w.kind==='font_coverage');}
function canKeep(w){return !isFont(w)||w.glyphSupported===true;}
function decorateWarnings(ws){return(ws||[]).map(w=>{if(!isFont(w))return w;const c=context(w.original||w.text||'',w.codePoint);return{...w,groupKey:groupKey(w),problemType:'Нестандартний символ шрифту',context:c,allowKeep:canKeep(w),keepDisabledReason:canKeep(w)?'':'Цей символ неможливо залишити без змін, оскільки PDF-шрифт його не підтримує. Оберіть «Замінити» або «Прибрати».'};});}
function palette(container,input,onPick){const box=document.createElement('div');box.className='greek-palette';for(const [ch,name] of GREEK){const b=document.createElement('button');b.type='button';b.className='greek-key';b.title=`${ch} — ${name}`;b.setAttribute('aria-label',`${ch} — ${name}`);const glyph=document.createElement('strong');glyph.textContent=ch;const label=document.createElement('small');label.textContent=name;b.append(glyph,label);b.addEventListener('click',()=>{input.value=ch;input.dispatchEvent(new Event('input',{bubbles:true}));if(onPick)onPick(ch,name);});box.appendChild(b);}container.appendChild(box);return box;}
function fontHasCodePoint(font,n){if(font&&typeof font.hasCodePoint==='function')return Boolean(font.hasCodePoint(n));if(font&&typeof font.glyphFor==='function')return n===0||font.glyphFor(n)!==0;return false;}
function standardGreekSupported(font){const lower=[];for(let n=0x03B1;n<=0x03C9;n++){if(n===0x03C2)continue;if(!fontHasCodePoint(font,n))lower.push(cp(String.fromCodePoint(n)));}const upper=[];for(const ch of 'ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩ')if(!fontHasCodePoint(font,ch.codePointAt(0)))upper.push(cp(ch));return{ok:!lower.length&&!upper.length,lower,upper};}
root.JournalV123={GREEK,context,groupKey,isFont,canKeep,decorateWarnings,palette,fontHasCodePoint,standardGreekSupported};
})(typeof globalThis!=='undefined'?globalThis:self);