(function(root){'use strict';
const V='1.2.4';
function fontHasCodePoint(font,cp){if(font&&typeof font.hasCodePoint==='function')return Boolean(font.hasCodePoint(cp));if(font&&typeof font.glyphFor==='function')return cp===0||font.glyphFor(cp)!==0;return false;}
if(root.JournalPdf?.TrueTypeFont&&!root.JournalPdf.TrueTypeFont.prototype.hasCodePoint){root.JournalPdf.TrueTypeFont.prototype.hasCodePoint=function(cp){return cp===0||this.glyphFor(cp)!==0;};}
if(root.JournalV123){root.JournalV123.fontHasCodePoint=fontHasCodePoint;root.JournalV123.standardGreekSupported=function(font){const lower=[];for(let n=0x03B1;n<=0x03C9;n++){if(n===0x03C2)continue;if(!fontHasCodePoint(font,n))lower.push(`U+${n.toString(16).toUpperCase().padStart(4,'0')}`);}const upper=[];for(const ch of 'ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩ')if(!fontHasCodePoint(font,ch.codePointAt(0)))upper.push(`U+${ch.codePointAt(0).toString(16).toUpperCase().padStart(4,'0')}`);return{ok:!lower.length&&!upper.length,lower,upper};};}
// v1.2.3 parser used Math.max(...map.keys/values), which can overflow the JS argument stack on very large formatted sheets.
// Keep every cell, but make only the max-row/max-col iterator used during parsing constant-size. The original Map methods are restored immediately.
if(root.JournalWorkbook?.parseWorkbook){const originalParse=root.JournalWorkbook.parseWorkbook.bind(root.JournalWorkbook);root.JournalWorkbook.parseWorkbook=async function(buf,file){const keys=Map.prototype.keys,values=Map.prototype.values;Map.prototype.keys=function(){if(this.size>50000){let max=0,allNumeric=true;for(const k of keys.call(this)){if(typeof k!=='number'){allNumeric=false;break;}if(k>max)max=k;}if(allNumeric)return[max][Symbol.iterator]();}return keys.call(this);};Map.prototype.values=function(){if(this.size>50000){let maxCell=null,maxCol=-1,cellMap=true;for(const v of values.call(this)){if(!v||typeof v!=='object'||typeof v.col!=='number'){cellMap=false;break;}if(v.col>maxCol){maxCol=v.col;maxCell=v;}}if(cellMap&&maxCell)return[maxCell][Symbol.iterator]();}return values.call(this);};try{return await originalParse(buf,file);}finally{Map.prototype.keys=keys;Map.prototype.values=values;}};}
const oldReport=root.JournalValidation?.buildTechnicalReport;if(oldReport){root.JournalValidation.buildTechnicalReport=function(r={}){return oldReport({...r,version:V});};}
root.JournalV124={VERSION:V,fontHasCodePoint};
})(typeof globalThis!=='undefined'?globalThis:self);