(function(root){'use strict';
const V='1.2.7',JP=root.JournalPdf;if(!JP||typeof JP.generatePdf!=='function')return;const original=JP.generatePdf.bind(JP);const enc=new TextEncoder();
function txt(cell){if(!cell)return'';if(cell.pdfText!=null)return String(cell.pdfText).trim();if(cell.text!=null)return String(cell.text).trim();if(Array.isArray(cell.sources))return cell.sources.map(s=>s?.pdfText??s?.text??'').join('').trim();return'';}
function hasMarks(row){return Array.isArray(row?.marks)&&row.marks.some(c=>txt(c)!=='');}
function cleanDisciplines(ds){return(ds||[]).map(d=>{if(!d?.grade?.students)return d;const students=d.grade.students.filter(r=>txt(r.name)!==''||hasMarks(r));return{...d,grade:{...d.grade,students}};});}
function ascii(s){return enc.encode(s);}function concat(parts){const n=parts.reduce((a,b)=>a+b.length,0),o=new Uint8Array(n);let p=0;for(const b of parts){o.set(b,p);p+=b.length;}return o;}function hex(bytes){let s='';for(const b of bytes)s+=b.toString(16).padStart(2,'0');return s.toUpperCase();}function num(n){return Number(n).toFixed(3).replace(/\.000$/,'').replace(/(\.\d*?)0+$/,'$1');}function utf16Hex(cp){if(cp<=0xffff)return cp.toString(16).padStart(4,'0').toUpperCase();const x=cp-0x10000,hi=0xd800+(x>>10),lo=0xdc00+(x&0x3ff);return hi.toString(16).padStart(4,'0').toUpperCase()+lo.toString(16).padStart(4,'0').toUpperCase();}function scale1000(n,u){return Math.round(Number(n||0)*1000/u);}function escName(n){return String(n).replace(/[^A-Za-z0-9_.-]/g,'-');}
function findAscii(bytes){return new TextDecoder('latin1').decode(bytes);}function lastMatch(re,s){let m,last=null;while((m=re.exec(s)))last=m;return last;}
function titleCommands(font,group,year){const W=JP.A4.width,H=JP.A4.height,cmd=[];function line(text,y,size){const t=String(text||'');if(!t)return;const x=(W-font.width(t,size))/2;cmd.push(`BT /F2 ${num(size)} Tf 0 0 0 rg 1 0 0 1 ${num(x)} ${num(y)} Tm <${hex(font.encode(t))}> Tj ET`);}line('ЖУРНАЛ ОБЛІКУ РОБОТИ',H*0.66,20);line('АКАДЕМІЧНОЇ ГРУПИ',H*0.59,20);line(`Група — ${group||'—'}`,H*0.43,14);line(`Навчальний рік — ${year||'—'}`,H*0.35,14);return ascii(cmd.join('\n')+'\n');}
function toUnicode(font){const pairs=Array.from(font.usedGlyphs.entries()).filter(([g])=>g!==0).sort((a,b)=>a[0]-b[0]),lines=[];for(let i=0;i<pairs.length;i+=100){const c=pairs.slice(i,i+100);lines.push(`${c.length} beginbfchar`);for(const[g,cp]of c)lines.push(`<${g.toString(16).padStart(4,'0').toUpperCase()}> <${utf16Hex(cp)}>`);lines.push('endbfchar');}return ascii(`/CIDInit /ProcSet findresource begin\n12 dict begin\nbegincmap\n/CIDSystemInfo << /Registry (Adobe) /Ordering (UCS) /Supplement 0 >> def\n/CMapName /JP127-UCS def\n/CMapType 2 def\n1 begincodespacerange\n<0000> <FFFF>\nendcodespacerange\n${lines.join('\n')}\nendcmap\nCMapName currentdict /CMap defineresource pop\nend\nend\n`);}
function widths(font){const gs=Array.from(font.usedGlyphs.keys()).filter(g=>g!==0).sort((a,b)=>a-b),groups=[];let cur=[];for(const g of gs){if(!cur.length||g===cur[cur.length-1]+1)cur.push(g);else{groups.push(cur);cur=[g];}}if(cur.length)groups.push(cur);return groups.map(g=>`${g[0]} [${g.map(x=>font.pdfWidth(x)).join(' ')}]`).join(' ');}
function stream(dict,bytes){return concat([ascii(`<< ${dict} /Length ${bytes.length} >>\nstream\n`),bytes,ascii('\nendstream')]);}
function prependTitle(pdfBytes,fontBytes,group,year){const s=findAscii(pdfBytes),pages=lastMatch(/(\d+) 0 obj\s*<< \/Type \/Pages \/Kids \[([^\]]*)\] \/Count (\d+) >>\s*endobj/g,s),trail=lastMatch(/trailer\s*<<([^>]*)>>\s*startxref\s*(\d+)\s*%%EOF/g,s);if(!pages||!trail)throw new Error('Не вдалося додати титульну сторінку: структура PDF не розпізнана.');const rootM=/\/Root\s+(\d+)\s+0\s+R/.exec(trail[1]),sizeM=/\/Size\s+(\d+)/.exec(trail[1]);if(!rootM||!sizeM)throw new Error('Не вдалося прочитати PDF trailer для титульної сторінки.');const pagesId=+pages[1],oldKids=pages[2].trim(),oldCount=+pages[3],oldXref=+trail[2],start=+sizeM[1],font=new JP.TrueTypeFont(fontBytes),content=titleCommands(font,group,year),fontFileId=start,toUniId=start+1,descId=start+2,cidId=start+3,type0Id=start+4,contentId=start+5,pageId=start+6,newSize=start+7,objects=[];
const push=(id,b)=>objects.push({id,bytes:b instanceof Uint8Array?b:ascii(b)});push(pagesId,`<< /Type /Pages /Kids [${pageId} 0 R ${oldKids}] /Count ${oldCount+1} >>`);push(fontFileId,stream(`/Length1 ${fontBytes.length}`,fontBytes));push(toUniId,stream('',toUnicode(font)));const bbox=[font.xMin,font.yMin,font.xMax,font.yMax].map(x=>scale1000(x,font.unitsPerEm));push(descId,`<< /Type /FontDescriptor /FontName /${escName('Tinos-Regular')} /Flags 4 /FontBBox [${bbox.join(' ')}] /ItalicAngle 0 /Ascent ${scale1000(font.ascent,font.unitsPerEm)} /Descent ${scale1000(font.descent,font.unitsPerEm)} /CapHeight ${scale1000(font.ascent,font.unitsPerEm)} /StemV 80 /FontFile2 ${fontFileId} 0 R >>`);push(cidId,`<< /Type /Font /Subtype /CIDFontType2 /BaseFont /${escName('Tinos-Regular')} /CIDSystemInfo << /Registry (Adobe) /Ordering (Identity) /Supplement 0 >> /FontDescriptor ${descId} 0 R /DW 1000 /W [${widths(font)}] /CIDToGIDMap /Identity >>`);push(type0Id,`<< /Type /Font /Subtype /Type0 /BaseFont /${escName('Tinos-Regular')} /Encoding /Identity-H /DescendantFonts [${cidId} 0 R] /ToUnicode ${toUniId} 0 R >>`);push(contentId,stream('',content));push(pageId,`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${num(JP.A4.width)} ${num(JP.A4.height)}] /Resources << /Font << /F2 ${type0Id} 0 R >> >> /Contents ${contentId} 0 R >>`);
let pos=pdfBytes.length,parts=[pdfBytes,ascii('\n')],offsets=new Map();pos+=1;for(const o of objects){offsets.set(o.id,pos);const h=ascii(`${o.id} 0 obj\n`),t=ascii('\nendobj\n');parts.push(h,o.bytes,t);pos+=h.length+o.bytes.length+t.length;}const xrefPos=pos,newIds=objects.filter(o=>o.id>=start).map(o=>o.id).sort((a,b)=>a-b);let x=`xref\n${pagesId} 1\n${String(offsets.get(pagesId)).padStart(10,'0')} 00000 n \n${start} ${newIds.length}\n`;for(const id of newIds)x+=`${String(offsets.get(id)).padStart(10,'0')} 00000 n \n`;x+=`trailer\n<< /Size ${newSize} /Root ${rootM[1]} 0 R /Prev ${oldXref} >>\nstartxref\n${xrefPos}\n%%EOF\n`;parts.push(ascii(x));return concat(parts);}
JP.generatePdf=async function(disciplines,overrides={},options={}){const cleaned=cleanDisciplines(disciplines),r=await original(cleaned,overrides,options),fb=options.fontBytes instanceof Uint8Array?options.fontBytes:new Uint8Array(options.fontBytes||[]);if(!fb.length)return r;const bytes=prependTitle(r.bytes,fb,options.group||'',options.academicYear||root.__journalAcademicYear||'');return{...r,bytes,pages:r.pages+1,pageInfo:[{kind:'title',subject:'Титульна сторінка'},...(r.pageInfo||[])]};};
const oldAdd=root.addEventListener?.bind(root);if(oldAdd&&typeof WorkerGlobalScope!=='undefined'&&root instanceof WorkerGlobalScope){root.addEventListener=function(type,handler,opts){if(type!=='message')return oldAdd(type,handler,opts);return oldAdd(type,function(e){if(e?.data?.type==='generate')root.__journalAcademicYear=String(e.data.academicYear||'').trim();return handler.call(this,e);},opts);};}
root.JournalV127Pdf={VERSION:V,cleanDisciplines,prependTitle};
})(typeof globalThis!=='undefined'?globalThis:self);
